name: Deploy
on:
  push:
    branches:
      - '**'
    tags:
    - '**'
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hello World
        run: echo Hello, world!