# This is a basic workflow that is manually triggered

name: Promote to Upper Environment

on:
  workflow_dispatch:
    inputs:
      from_version:
        description: 'From Version Tag:'
        default: ''
        required: true
      to_version:
        description: 'To Version Tag:'
        default: ''
        required: true
      message:
        description: 'Message:'
        default: 'chore(release): ...'
        required: true
      to_env:
        type: choice
        required: true
        description: 'To Env: '
        default: 'qa'
        options:
        - qa
        - stg
        - prod

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: "Promote to Upper Environment"
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git pull
          git fetch --tags
          git checkout tags/${{github.event.inputs.from_version}}
          git commit --allow-empty --allow-empty-message -m ""
          git tag -a ${{github.event.inputs.to_version}} -m "${{ github.event.inputs.message }}"
          git push origin ${{github.event.inputs.to_version}}
  ru_regresion:
    uses: carlosvegaUnivision/test/.github/workflows/share.yml@main
    with:
      environment_id: ${{ github.event.inputs.to_env }}
    secrets:
      POSTMAN_TOKEN: ${{ secrets.POSTMAN }}

