# This is a basic workflow that is manually triggered

name: Promote to Upper Environment

on:
  workflow_dispatch:
    inputs:
      from:
        type: choice
        required: true
        description: 'From: '
        default: 'Dev'
        options:
        - Dev
        - QA
        - STG
      version:
        description: 'Version:'
        default: ''
        required: true
      to:
        type: choice
        required: true
        description: 'To: '
        default: 'QA'
        options:
        - QA
        - STG
        - PROD
      message:
        description: 'Message:'
        default: 'chore(release): ...'
        required: true

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: "Promote to Upper Environment"
        run: |
          echo "From ${{ github.event.inputs.from }}"
          echo "Version is ${{ github.event.inputs.version }}"
          echo "To is ${{ github.event.inputs.to }}"
          echo git describe --tags
          echo "Message is ${{ github.event.inputs.message }}"

