# This is a basic workflow that is manually triggered

name: Promote to Upper Environment

on:
  workflow_dispatch:
    inputs:
      from:
        type: choice
        required: true
        description: 'From: '
        default: 'Dev'
        options:
        - Dev
        - QA
        - STG
      version:
        description: 'Version:'
        default: ''
        required: true
      to:
        type: choice
        required: true
        description: 'To: '
        default: 'QA'
        options:
        - QA
        - STG
        - PROD
      message:
        description: 'Message:'
        default: 'chore(release): ...'
        required: true

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: "Promote to Upper Environment"
        run: |
          git config --global user.email "u1200112@unimilitar.edu.co"
          git config --global user.name "Carlos Vega"
          git pull
          git fetch --tags
          git checkout tags/v1.3.0
          git commit --allow-empty --allow-empty-message -m "dddd"
          git tag -a 1.3.0-beta -m "dddd"
          git push origin 1.3.0-beta
          echo "From ${{ github.event.inputs.from }}"
          echo "Version is ${{ github.event.inputs.version }}"
          echo "To is ${{ github.event.inputs.to }}"
          git describe --tags
          echo "Message is ${{ github.event.inputs.message }}"

